services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: academ
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./.mysql-data:/var/lib/mysql

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    depends_on:
      - redis
      - mysql
    ports:
      - "8080:8080"
    environment:
      - PROFILE=production

