academ:
  version: "v1.1.3"

spring:

  ## application 기본 이름 설정
  application:
    name: Academ_back

  ## 데이터베이스(MySQL) 연동
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # update 수정 필요

  ## Google SMTP server
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true      # 사용자 인증 시도 여부
          timeout: 5000   # socket read timeout 시간(ms)
          starttls:
            enable: true  # StartTLS 활성화 여부

  ## Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

## JWT 설정
jwt:
  secret: ${JWT_SECRET}               # Base64
  access_expiration_time: 3600        # Access token 만료 시간 : 60분
  refresh_expiration_time: 2592000    # Refresh token 만료 시간 : 30일

## Swagger 설정
springdoc:
  override-with-generic-response: true
  use-fqn: true   # dto 구분 여부
  default-consumes-media-type: application/json   # 소비 미디어 타입
  default-produces-media-type: application/json   # 생산 미디어 타입
  swagger-ui:
    operations-sorter: method   # operations 정렬 방식