academ:
  version: "v0.3.21-alpha"

## 데이터베이스(MySQL) 연동
spring:
  application:
    name: Devkor_project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update # update 수정 필요
    properties:
      hibernate:
        format_sql: true  # JPA 로그 이쁘게 구조화
  security:
    user:
      name: kk@kk
      password: kkkk
      

  ## Google SMTP server
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true      # 사용자 인증 시도 여부
          timeout: 5000   # socket read timeout 시간(ms)
          starttls:
            enable: true  # StartTLS 활성화 여부

## JPA 로깅 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug        # 디버그 레벨로 쿼리 출력
        orm:
          jdbc:
            bind: trace   # 쿼리의 파라미터 출력

### 서버 세션 관리
server:
  servlet:
    session:
      timeout: 60m
      cookie:             # 쿠키 관련 설정
        secure: true      # 로컬에서 http로 테스트하는 경우 false
        same-site: None