academ:
  version: "v1.0.1"

spring:

  ## application 기본 이름 설정
  application:
    name: Academ_back

  ## 데이터베이스(MySQL) 연동
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update # update 수정 필요
    properties:
      hibernate:
        format_sql: true  # JPA 로그 이쁘게 구조화

  ## Google SMTP server
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true      # 사용자 인증 시도 여부
          timeout: 5000   # socket read timeout 시간(ms)
          starttls:
            enable: true  # StartTLS 활성화 여부

  ## Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

## JPA 로깅 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug        # 디버그 레벨로 쿼리 출력
        orm:
          jdbc:
            bind: trace   # 쿼리의 파라미터 출력

## JWT 설정
jwt:
  # Base64
  secret: ${JWT_SECRET}
  access_expiration_time: 3600        # 60분
  refresh_expiration_time: 2592000    # 30일

## 애플리케이션 유휴 제한 시간 설정 (로드 밸런싱 관련 오류 해결)
server:
  tomcat:
    keep-alive-timeout: 190_000       # 190초