name: Deploy to GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Create .properties file
      run: |
        touch ./src/main/resources/application-production.properties
        echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application-production.properties
        touch ./src/main/resources/application.properties
        echo "${{ secrets.PROPERTIES_DEV }}" > ./src/main/resources/application.properties

    - name: Change permission of gradle
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build --exclude-task test

    - name: Build and push Docker image
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      run: |
        echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
        IMAGE_TAG=$(echo ${{ github.ref_name }} | sed 's/^v//')
        docker build -t ghcr.io/devkor-github/academ-back:latest .
        docker push ghcr.io/devkor-github/academ-back:latest
        docker build -t ghcr.io/devkor-github/academ-back:${IMAGE_TAG} .
        docker push ghcr.io/devkor-github/academ-back:${IMAGE_TAG}
